name: CD

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Deploying ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux64]
        include:
          - build_target: linux64
            os: ubuntu-latest
            artifact_suffix: linux-x86_64
            target_arch: amd64
            target_os: linux
    env:
      DESTDIR: ./${{ matrix.artifact_suffix }}
    steps:
      - name: Set up access
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Update
        run: go mod tidy && go mod vendor
      - name: Build
        run: GOOS=${{ matrix.target_os }} GOARCH=${{ matrix.target_arch }} go build -o gauth-${{ matrix.artifact_suffix }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gauth-${{ matrix.artifact_suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
